In [1]:
import requests 
import json
import tqdm
import pandas as pd

url = 'https://dawa.aws.dk/supplerendebynavne2' 
response = requests.get(url, 'html.parsing').json()

In [10]:
COL = ['Kommune', 'By', 'Postnr1', 'Postnr2', 'Postnr3', 'Postnr4']

df = pd.DataFrame(columns = COL)

for i in tqdm.tqdm(response):
    try:
        df = df.append({'Kommune': i['kommune']['navn'],
                       'By': i['navn'],
                       'Postnr1': i['postnumre'][0]['nr'],
                       'Postnr2': i['postnumre'][1]['nr'],
                       'Postnr3': i['postnumre'][2]['nr'],
                       'Postnr4': i['postnumre'][3]['nr']}, ignore_index = True)
        
    except: 
        try:
            df = df.append({'Kommune': i['kommune']['navn'],
                            'By': i['navn'],
                            'Postnr1': i['postnumre'][0]['nr'],
                            'Postnr2': i['postnumre'][1]['nr'],
                            'Postnr3': i['postnumre'][2]['nr']}, ignore_index = True)
        except: 
            try:
                df = df.append({'Kommune': i['kommune']['navn'],
                                    'By': i['navn'],
                                    'Postnr1': i['postnumre'][0]['nr'],
                                    'Postnr2': i['postnumre'][1]['nr']}, ignore_index = True)
            except:
                try:
                    df = df.append({'Kommune': i['kommune']['navn'],
                                    'By': i['navn'],
                                    'Postnr1': i['postnumre'][0]['nr']}, ignore_index = True)
                except:
                    None

100%|██████████| 7880/7880 [00:58<00:00, 134.42it/s]

In [64]:
response[1]['postnumre']

[{'href': 'https://dawa.aws.dk/postnumre/2680',
  'navn': 'Solrød Strand',
  'nr': '2680'},
 {'href': 'https://dawa.aws.dk/postnumre/4622',
  'navn': 'Havdrup',
  'nr': '4622'}]

In [73]:
df = pd.DataFrame()


for i in tqdm.tqdm(range(200)):
    split = response[i]
    count = 1
    for nr in split['postnumre']:
            df = df.append({'Kommune': split['kommune']['navn'],
                    'By': split['navn'],
                    'Postnr': [pn['nr'] for pn in split['postnumre']] }, ignore_index = True)
            count += 1

  0%|          | 0/200 [00:00<?, ?it/s]
 16%|█▌        | 31/200 [00:00<00:00, 303.87it/s]
 32%|███▏      | 63/200 [00:00<00:00, 308.21it/s]
 48%|████▊     | 95/200 [00:00<00:00, 307.23it/s]
 64%|██████▎   | 127/200 [00:00<00:00, 309.25it/s]
 78%|███████▊  | 157/200 [00:00<00:00, 304.92it/s]
 93%|█████████▎| 186/200 [00:00<00:00, 298.92it/s]
100%|██████████| 200/200 [00:00<00:00, 291.29it/s]

In [74]:
df

                   By        Kommune              Postnr
0             Havdrup         Solrød              [4622]
1              Solrød         Solrød        [2680, 4622]
2              Solrød         Solrød        [2680, 4622]
3        Kongsh Mølle         Nyborg              [5871]
4             Aunslev         Nyborg              [5800]
5                Måre         Nyborg              [5853]
6        Tårup Strand         Nyborg              [5871]
7          Strandskov         Nyborg              [5800]
8             Rosilde         Nyborg              [5800]
9             Såderup         Nyborg        [5540, 5853]
10            Såderup         Nyborg        [5540, 5853]
11              Slude         Nyborg              [5871]
12              Visby         Nyborg              [5540]
13           Kullerup         Nyborg              [5853]
14         Knudshoved         Nyborg              [5800]
15          Nørrehede       Aabenraa              [6230]
16         Skedebjerg       Aabenraa              [6200]
17      Frestrup Mark       Aabenraa              [6360]
18           Vollerup       Aabenraa              [6392]
19           Nr Ønlev       Aabenraa              [6230]
20        Hostrupskov       Aabenraa              [6200]
21              Nykro       Aabenraa              [6230]
22          Sdr Ønlev       Aabenraa              [6230]
23               Heds       Aabenraa              [6360]
24           Uge Mark       Aabenraa              [6360]
25           Bylderup       Aabenraa              [6372]
26               Søst       Aabenraa              [6230]
27       Gårdeby Mark       Aabenraa              [6360]
28          Nybølmark       Aabenraa              [6230]
29              Raved       Aabenraa              [6392]
..                ...            ...                 ...
193          Kragerup     Kalundborg  [4200, 4291, 4293]
194           Tågerup     Kalundborg              [4291]
195        Vallekilde     Kalundborg              [4534]
196              Løve     Kalundborg              [4270]
197          Torsmark          Skive              [7860]
198            Estvad          Skive              [7800]
199      Estvadg Mark          Skive              [7800]
200      Gørlev Ornum     Kalundborg              [4281]
201         Knudstrup     Kalundborg              [4270]
202          Tolstrup          Skive              [7800]
203         Tøndering          Skive              [7870]
204          Holmgård  Mariagerfjord              [8990]
205       S Onsild Kb  Mariagerfjord              [9500]
206         Kjellerup  Mariagerfjord              [9550]
207             Kulby     Kalundborg        [4270, 4291]
208             Kulby     Kalundborg        [4270, 4291]
209            Glerup  Mariagerfjord        [9510, 9560]
210            Glerup  Mariagerfjord        [9510, 9560]
211        Gundestrup  Mariagerfjord        [8990, 9500]
212        Gundestrup  Mariagerfjord        [8990, 9500]
213       Glentehaven     Kalundborg              [4270]
214        Havnsø Str     Kalundborg              [4591]
215  Bjerge Sydstrand     Kalundborg        [4281, 4480]
216  Bjerge Sydstrand     Kalundborg        [4281, 4480]
217           Nørager     Kalundborg              [4291]
218          Forsinge     Kalundborg        [4470, 4490]
219          Forsinge     Kalundborg        [4470, 4490]
220           Nautrup          Skive              [7870]
221          Gåsemose          Skive              [7870]
222            Kyndby  Frederikssund              [3630]

[223 rows x 3 columns]

In [27]:
COL = ['Kommune', 'By']

df = pd.DataFrame(columns = COL)

for i in tqdm.tqdm(response):
    for nr in i['postnumre']:
        df = df.append({'Kommune': i['kommune']['navn'],
                        'By': i['navn'],
                        'Postnr{x}'.format(x = nr): ['nr']}, ignore_index = True)

 32%|███▏      | 2493/7880 [04:19<19:13,  4.67it/s]

KeyboardInterrupt:

In [24]:
df.iloc[(df.By == 'København') == True]

NotImplementedError: iLocation based boolean indexing on an integer type is not available

In [19]:
df['Postnr4'].isna().sum()

7871

In [24]:
df_nodub.to_csv('By_Postnr_Kommune.csv')